spring:
  application:
    name: notifications
  mail:
    host: smtp.gmail.com
    port: 587
    username: shilohtheophilus189@gmail.com
    password: uhjr taoo rzdi ufhc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9000

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
