spring:
  application:
    name: transactions
  datasource:
    url: jdbc:postgresql://localhost:5432/theo-transactions
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
